### ISSUE TITLE
If with command --listen, plug-in will show error

### ISSUE THREAD

**Issue by IzumoNoOkuni** [OedoSoldier/enhanced-img2img#12]
I'm running WebUI from my server, so I turned the local IP access link on. In webui-user.bat I set 
```set COMMANDLINE_ARGS= --listen```

After I open the local IP in another computer, after every setting set up then hit Generate, It will show error
`FileNotFoundErrir: [Eeeno 2] No such file or directory: 'E:\\stable-difusion\\extensions/enhanced-img2img/scripts/util.py'`

On the computer I use locally, Stable Diffusion is not installed in the E:\\ drive. But in my server, I put my stable diffusion in the E:\\ drive. So the folder information it reads is from the E drive of the server, but for some reason it wants to read the information from the E drive of my local computer.

**Comment by OedoSoldier** [comment]
Fix #14
