### ISSUE TITLE
AssertionError when using "Use another image as ControlNet input"

### ISSUE THREAD

**Issue by rafalePOP** [OedoSoldier/enhanced-img2img#24]
When using multi-frame rendering and attempting to read in a depth map using another image as ControlNet input, the following error occurs
Is this an error on the controlnet side?

Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 687, in process
    input_image = HWC3(np.asarray(p_input_image).astype(np.uint8))
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\util.py", line 6, in HWC3
    assert x.dtype == np.uint8
AssertionError

**Comment by OedoSoldier** [comment]
When loading another image you should select none for annotators.

**Comment by rafalePOP** [comment]
If I'm not mistaken, I think the annotator can be omitted. After this, select multi-frame rendering in the script and check "Use another image as ControlNet input", and specify the directory for only the depth map.
Sorry if the text is incorrect as it is translated by deepl.
![Desktop Screenshot 2023 04 06 - 01 52 02 17](https://user-images.githubusercontent.com/109017050/230150560-ea08ce6c-c43d-4505-82a8-16717ea7c006.png)
