### ISSUE TITLE
Instructions unclear for the `Read tabular command` option

### ISSUE THREAD

**Issue by HeavyTony2** [OedoSoldier/enhanced-img2img#5]
First of all, the readme is clearly outdated since the option doesn't even have the same name anymore and Excel files are supported. 

Secondly, explanations aren't sufficient. As users we're not warned the first line will be treated as the header. Are we supposed to expect to have the prompt chosen according to the file name alphabetical rank?

Also, I've a suggestion: there could be an option for tag in the filenames.

**Comment by OedoSoldier** [comment]
Reading tags from text files is now supported.
