### ISSUE TITLE
Why is my process sorting the images by random number instead of in a sequential order?

### ISSUE THREAD

**Issue by wicebing** [OedoSoldier/enhanced-img2img#9]
Although my PNG files are named sequentially from 00000.png to 00584.png, the processing is being done in a random order instead of in the correct sequence. 

Anyway, thank you very much for your method of video m2m. It's great work. I had an idea of adapting the SD model, and I see that you've already done it.

**Comment by wicebing** [comment]
Maybe could add "images.sort()" at [line 247] or [line 288] of enhanced-img2img.py to ensure the images are sorted before processing them.

reference_imgs.sort() to line 97 in multi-frame_render.py

**Comment by OedoSoldier** [comment]
Good idea, added #11
